version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on $(date +%Y-%m-%d)
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
